# "2024-05-30-Custom Jupyter Display NDArray Shapes"

# Problem: NDArray shapes are tedious to print!!

# Solution: Customize their display in the notebook by setting a custom formatter!!

In [ ]:
# Observation: Sometimes specific result can be successfully picked while entire pipeline cannot:
# from pyphoplacecellanalysis.General.Pipeline.Stages.ComputationFunctions.MultiContextComputationFunctions.RankOrderComputations import save_rank_order_results, SaveStringGenerator
from typing import Dict, List, Tuple, Optional, Callable, Union, Any
from typing_extensions import TypeAlias
from neuropy.core import Epoch
from nptyping import NDArray
import neuropy.utils.type_aliases as types

import numpy as np
import pandas as pd
from attrs import define, field, Factory, asdict, astuple
from functools import wraps
from copy import deepcopy
from collections import namedtuple
from pathlib import Path
from datetime import datetime, date, timedelta
from neuropy.utils.mixins.AttrsClassHelpers import AttrsBasedClassHelperMixin, custom_define, serialized_field, serialized_attribute_field, non_serialized_field, keys_only_repr

## Text-only Represntation that prints size:

In [12]:
import numpy as np
from IPython.display import display, HTML

def array_preview_with_shape(arr):
    """ Text-only Represntation that prints np.shape(arr) """
    if isinstance(arr, np.ndarray):
        display(HTML(f"<pre>array{arr.shape} of dtype {arr.dtype}</pre>"))
    elif isinstance(arr, (list, tuple)):
        display(HTML(f"<pre>native-python list {len(arr)}</pre>"))
    elif isinstance(arr, pd.DataFrame):
        display(HTML(f"<pre>DataFrame with {len(arr)} rows and {len(arr.columns)} columns</pre>"))
    else:
        raise ValueError("The input is not a NumPy array.")

# Register the custom display function for numpy arrays
import IPython
ip = IPython.get_ipython()
ip.display_formatter.formatters['text/html'].for_type(np.ndarray, array_preview_with_shape) # only registers for NDArray

# Example usage
arr = np.random.rand(3, 4)
display(arr)


array([[0.45903152, 0.54084321, 0.69628124, 0.83259053],
       [0.71067258, 0.84755403, 0.8285288 , 0.18378591],
       [0.03883732, 0.41551904, 0.84079938, 0.2367737 ]])

In [ ]:
import dask.array as da

da.ones((10, 10), chunks=(5, 5), dtype='i4')

In [4]:
da.ini

<module 'dask.array' from 'k:\\FastSwap\\AppData\\VSCode\\black\\.venv_black\\lib\\site-packages\\dask\\array\\__init__.py'>

In [7]:
import numpy as np
import dask.array as da
from IPython.display import display, HTML

def array_preview_with_graphical_shape_repr_html(arr):
    """Generate an HTML representation for a NumPy array, similar to Dask."""
    if isinstance(arr, np.ndarray):
        arr = da.array(arr)
        return display(arr)
        # shape_str = ' &times; '.join(map(str, arr.shape))
        # dtype_str = arr.dtype
        # return f"<pre>array[{shape_str}] dtype={dtype_str}</pre>"
    else:
        raise ValueError("The input is not a NumPy array.")

# Register the custom display function for NumPy arrays
import IPython
ip = IPython.get_ipython()
ip.display_formatter.formatters['text/html'].for_type(np.ndarray, lambda arr: array_preview_with_graphical_shape_repr_html(arr))

# Example usage
arr = np.random.rand(3, 4)
display(arr)


arr = np.random.rand(9, 64)
display(arr)

arr = np.random.rand(9, 64, 4)
display(arr)

dask.array<array, shape=(3, 4), dtype=float64, chunksize=(3, 4), chunktype=numpy.ndarray>

array([[0.40424884, 0.83698904, 0.5743785 , 0.56369769],
       [0.10782416, 0.73019459, 0.75880909, 0.94826354],
       [0.18259298, 0.72275277, 0.98727248, 0.10837008]])

dask.array<array, shape=(9, 64), dtype=float64, chunksize=(9, 64), chunktype=numpy.ndarray>

array([[1.12757971e-01, 1.08610769e-01, 4.88752427e-01, 6.02184945e-01,
        6.52582578e-01, 5.26725263e-01, 7.21953982e-01, 8.75999199e-01,
        2.33221341e-01, 7.52521160e-01, 5.75769444e-01, 2.71418129e-01,
        9.76444662e-01, 7.32942461e-01, 9.48748546e-01, 5.63813597e-01,
        1.94014639e-01, 2.76112037e-01, 9.55476644e-01, 5.85563112e-01,
        7.50816887e-01, 2.70708394e-01, 9.57779081e-01, 9.49076645e-01,
        9.25902035e-01, 2.08501922e-02, 6.70798921e-01, 6.15029676e-01,
        1.98511096e-02, 8.79908891e-01, 9.86685196e-04, 7.43394240e-01,
        9.30629745e-01, 8.24587587e-01, 2.80138240e-01, 8.29301711e-01,
        5.98737391e-02, 4.93737230e-01, 9.13653151e-01, 3.82651776e-01,
        7.62627944e-01, 7.17737760e-01, 8.38522951e-02, 7.97898293e-01,
        9.55656593e-01, 8.92563981e-01, 9.27274366e-01, 3.29680170e-01,
        7.28784711e-01, 5.15234985e-01, 9.85144451e-01, 3.96986798e-01,
        5.59921468e-01, 4.41497449e-01, 9.31028400e-01, 5.895920

dask.array<array, shape=(9, 64, 4), dtype=float64, chunksize=(9, 64, 4), chunktype=numpy.ndarray>

array([[[0.88788506, 0.45249424, 0.18426937, 0.25036931],
        [0.85181163, 0.22559092, 0.00314015, 0.87768976],
        [0.83941313, 0.16934126, 0.75471882, 0.33582448],
        ...,
        [0.63989305, 0.37303356, 0.22048901, 0.27212685],
        [0.12645837, 0.09808326, 0.13000282, 0.19798999],
        [0.49645288, 0.79730579, 0.81776111, 0.55692869]],

       [[0.87805913, 0.12782204, 0.45004792, 0.83444328],
        [0.05925258, 0.96498968, 0.81227439, 0.83696947],
        [0.98234743, 0.27639176, 0.40295026, 0.91039508],
        ...,
        [0.30898982, 0.04476975, 0.16139241, 0.81799585],
        [0.03993821, 0.47189635, 0.81163468, 0.2365261 ],
        [0.49938378, 0.54046037, 0.18490955, 0.9701591 ]],

       [[0.95684051, 0.08539798, 0.6912739 , 0.45991982],
        [0.40343651, 0.50832499, 0.75413622, 0.95207329],
        [0.20530374, 0.96126252, 0.06648125, 0.63614116],
        ...,
        [0.52669637, 0.20538215, 0.35746417, 0.82548605],
        [0.25244588, 0.804050

In [8]:
arr

dask.array<array, shape=(9, 64, 4), dtype=float64, chunksize=(9, 64, 4), chunktype=numpy.ndarray>

array([[[0.88788506, 0.45249424, 0.18426937, 0.25036931],
        [0.85181163, 0.22559092, 0.00314015, 0.87768976],
        [0.83941313, 0.16934126, 0.75471882, 0.33582448],
        ...,
        [0.63989305, 0.37303356, 0.22048901, 0.27212685],
        [0.12645837, 0.09808326, 0.13000282, 0.19798999],
        [0.49645288, 0.79730579, 0.81776111, 0.55692869]],

       [[0.87805913, 0.12782204, 0.45004792, 0.83444328],
        [0.05925258, 0.96498968, 0.81227439, 0.83696947],
        [0.98234743, 0.27639176, 0.40295026, 0.91039508],
        ...,
        [0.30898982, 0.04476975, 0.16139241, 0.81799585],
        [0.03993821, 0.47189635, 0.81163468, 0.2365261 ],
        [0.49938378, 0.54046037, 0.18490955, 0.9701591 ]],

       [[0.95684051, 0.08539798, 0.6912739 , 0.45991982],
        [0.40343651, 0.50832499, 0.75413622, 0.95207329],
        [0.20530374, 0.96126252, 0.06648125, 0.63614116],
        ...,
        [0.52669637, 0.20538215, 0.35746417, 0.82548605],
        [0.25244588, 0.804050

# Internally Dask array implements like: `https://github.com/dask/dask/blob/3432f4601eb7edc9cd5c2d64fd463d23ab4c3b25/dask/array/core.py#L79`


In [ ]:
    def _repr_html_(self):
        try:
            grid = self.to_svg(size=config.get("array.svg.size", 120))
        except NotImplementedError:
            grid = ""

        if "sparse" in typename(type(self._meta)):
            nbytes = None
            cbytes = None
        elif not math.isnan(self.nbytes):
            nbytes = format_bytes(self.nbytes)
            cbytes = format_bytes(math.prod(self.chunksize) * self.dtype.itemsize)
        else:
            nbytes = "unknown"
            cbytes = "unknown"

        return get_template("array.html.j2").render(
            array=self,
            grid=grid,
            nbytes=nbytes,
            cbytes=cbytes,
            layers=maybe_pluralize(len(self.dask.layers), "graph layer"),
        )

    def to_svg(self, size=500):
        """Convert chunks from Dask Array into an SVG Image

        Parameters
        ----------
        chunks: tuple
        size: int
            Rough size of the image

        Examples
        --------
        >>> x.to_svg(size=500)  # doctest: +SKIP

        Returns
        -------
        text: An svg string depicting the array as a grid of chunks
        """
        # from dask.array.svg import svg
        from .svg import svg

        return svg(self.chunks, size=size)