In [4]:
import numpy as np
from scipy import stats

from scipy.special import rel_entr # alternative

Note that the units used in this calculation are known as nats, which is short for natural unit of information

## Also see:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.rel_entr.html#scipy.special.rel_entr

https://www.statology.org/kl-divergence-python/

In [2]:
#define two probability distributions
P = [.05, .1, .2, .05, .15, .25, .08, .12]
Q = [.3, .1, .2, .1, .1, .02, .08, .1]

distributions = np.vstack((P, Q))
distributions

https://stackoverflow.com/questions/34007028/efficient-way-of-computing-kullback-leibler-divergence-in-python

In [7]:
# https://stackoverflow.com/questions/34007028/efficient-way-of-computing-kullback-leibler-divergence-in-python
# In our case, we are doing these entropy calculations for each *row* in `distributions` against all *rows*
kld = stats.entropy(distributions.T[:,:,None], distributions.T[:,None,:])
kld

# array([[0.        , 0.58988518],
#        [0.49754932, 0.        ]])

array([[0.        , 0.58988518],
       [0.49754932, 0.        ]])

In [3]:
# stats.entropy(distributions[0,None].T, distributions[1:].T)

array([[0.        , 0.58988518],
       [0.49754932, 0.        ]])

In [5]:
sum(rel_entr(P, Q)) # 0.589885181619163 nats

0.589885181619163

In [6]:
sum(rel_entr(Q, P)) # 0.497549319448034 nats

0.497549319448034